server:
  port: 18090
spring:

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 192.168.125.128
  datasource:
    url: jdbc:mysql://192.168.125.128:3306/guli_cart
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  task:
    execution:
      thread-name-prefix: cart-
      pool:
        core-size: 100
        max-size: 500
        keep-alive: 60S
        queue-capacity: 5000
        allow-core-thread-timeout: false
      shutdown:
        await-termination: true
        await-termination-period: 60
  rabbitmq:
    host: 192.168.125.128
    port: 5672
    username: jiege
    password: root
    virtual-host: /jiege
    listener:
      simple:
        concurrency: 4
        acknowledge-mode: manual
        prefetch: 1
feign:
  sentinel:
    enabled: true
#JWT配置
jwt:
  pubFilePath: E:\1130尚硅谷\01_谷粒商城0108\project\rsa.pub
  cookieName: GMALL-TOKEN
  userKey: userKey
  expire: 15552000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
