server:
  port: 18081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
    alibaba:
      seata:
        tx-service-group: tx-gmall-group
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.125.128:3306/guli_pms
    username: root
    password: root
  redis:
    host: 192.168.125.128
    port: 6379
  rabbitmq:
    host: 192.168.125.128
    port: 5672
    virtual-host: /jiege
    username: jiege
    password: root
    #确认消息是否到达对列
    publisher-returns: true
    #发布者确认
    publisher-confirm-type: correlated




mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.atguigu.gmall.pms.entity

feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug
