server:
  port: 18083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.125.128:3306/guli_wms
    username: root
    password: root
  redis:
    host: 192.168.125.128
    port: 6379




mybatis-plus:
  mapper-locations: classpath:mapper/wms/**/*.xml
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.atguigu.gmall.wms.entity

feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug